server:
  port: ${random.int[10000,19999]}

regCenter:
#  serverList: localhost:6181
  serverList: localhost:2181
  namespace: elastic-job-server
  
simpleJob:
  cron: 0/2 * * * * ?
  shardingTotalCount: 2
  shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou,3=Shanghai
  
dataflowJob:
  cron: 0/5 * * * * ?
  shardingTotalCount: 3
  shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou
